schema_version: 1

context:
  version: "26.9.0"

package:
  name: ansible-dev-environment
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ansible-dev-environment/ansible_dev_environment-${{ version }}.tar.gz
  sha256: b0cf0051bc4befee2339f0f5fb4a6cb4fd7117fc382d310ff2ae79fe0c7032db

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ade = ansible_dev_environment.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools-scm >=10.2,<10.3
    - setuptools >=80
  run:
    - python >=${{ python_min }}
    - ansible-builder >=3.1.0
    - bindep >=2.13.0
    - pyyaml >=6.0.1
    - subprocess-tee >=0.4.2

tests:
  - python:
      imports:
        - ansible_dev_environment
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  summary: |
    A pip-like ansible collection installer.
  homepage: https://pypi.org/project/ansible-dev-environment/
  repository: https://pypi.org/project/ansible-dev-environment/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
